### ISSUE TITLE
@content.downloadUrl property is missing

### ISSUE THREAD

**Issue by Mike-Bell** [OfficeDev/microsoft-graph-docs#42]
http://graph.microsoft.io/docs/api-reference/v1.0/api/item_downloadcontent suggests that items have a @content.downloadUrl property. I have yet to see this property show up on any request I've made. I seem to remember it being present when using the onedrive API, so this is probably a copy/paste bug with the docs.

**Comment by martellaj** [comment]
@Mike-Bell, thanks for the feedback!

@mimisasouvanh, can you please confirm whether or not `item` should have the `@content.downloadUrl` property or not?

**Comment by mimisasouvanh** [comment]
It should not. I'll make the correction.

**Comment by Mike-Bell** [comment]
@mimisasouvanh To clarify, are you suggesting that the @content.downloadUrl property should be available? I've tried several things to retrieve this property and nothing has worked. It doesn't come back as part of any item I've retrieved, and doing an explicit $select for it gives an error. @rgregg confirms this here https://github.com/OfficeDev/microsoft-graph-docs/issues/43

**Comment by Mike-Bell** [comment]
@martellaj Did we prematurely close this? I still have never been able to get a @content.downloadUrl out of the graph API, despite it being "supported" (I'm not sure to what extent it is supported - it seems like it's not at all). This seems to be confirmed here https://github.com/OfficeDev/microsoft-graph-docs/issues/43. Maybe I'm being a stickler, but I'm trying to keep track of unresolved issues on my end, and this one seems very much unresolved.

**Comment by martellaj** [comment]
@mimisasouvanh, @rgregg - can you help update @Mike-Bell on the status of this? Looks like there was a bug introduced between the time Mimi and Ryan answered. Thanks, all!

**Comment by rgregg** [comment]
There is still a bug that @content.downloadUrl isn't returned. The bug is being actively worked on by engineering right now, so this shouldn't be closed out yet.

**Comment by Mike-Bell** [comment]
As indicated here https://github.com/OfficeDev/microsoft-graph-docs/issues/43 this is now fixed. (though it's now called @microsoft.graph.downloadUrl)

**Comment by groetzi** [comment]
is `$select=content.downloadUrl` still supported? currently only getting property `@odata.context` in response when testing at `https://developer.microsoft.com/de-de/graph/graph-explorer`. `@microsoft.graph.downloadUrl` is still present when requesting the whole item though.
